apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: akovt8jsb-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/akovt8jsb-dotnet-basic-gitops